name: Xygeni Scan + Deployment
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      # TODO: añade aquí tus pasos de build (compilación, tests, etc.)

  xygeni-scan:
    runs-on: ubuntu-latest
    name: xygeni-github-action
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - name: Xygeni-Scanner
        uses: xygeni/xygeni-action@13c6ed2797df7d85749864e2cbcf09c893f43b23 # v6.4.0
        id: Xygeni-Scanner
        with:
          command: scan -n ${{ github.event.repository.name }} --dir ${{ github.workspace }}
          token: ${{ secrets.XYGENI_TOKEN }}
          gh_token: ${{ secrets.GH_PAT }}

  deployment:
    runs-on: ubuntu-latest
    name: deployment
    needs: xygeni-scan
    steps:
      # TODO: añade aquí tus pasos de despliegue
      - name: Deploy
        run: echo "Desplegando..."
